### ISSUE TITLE
show_text=true breaks widget

### ISSUE THREAD

**Issue by petersohn** [mokasin/apw#21]
The issue can be reproduced with the following (Awesome 4.1):
* Start out from the default Awesome `rc.lua`.
* Put the APW widget on the wibar (I tried it right after `mykeyboardlayout`).
* Set `show_text = true` (or `beautiful.apw_show_text = true`).

Without `show_text`, the widget works fine. If `show_text` is enabled, then it occupies almost the whole screen and does not update.

**Comment by mokasin** [comment]
Thx for your bug report. As stated in the README, I only maintain this project in a sense, that I'm willing to merge fixes via pull request. So you're welcome to fix this and file a pull request!

**Comment by mokasin** [comment]
Fixed by #22
